spring.datasource.url=jdbc:postgresql://localhost:5432/urlshortener
spring.datasource.username=urlshortener
spring.datasource.password=urlshortener
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.h2.console.enabled=false

app.base-url=https://url-shortener-upt2.onrender.com

app.jwt.secret=${APP_JWT_SECRET}
app.jwt.expiration-ms=86400000
